import SwiftUI
import AppKit
import MatchPostCore

struct EditingPreviewView: View {
    let placeholderImage: NSImage
    let exifDate: Date?
    let player: Player?
    let onAddToQueue: () -> Void
    let onCancel: () -> Void

    var body: some View {
        VStack(spacing: 0) {
            // Header
            HStack {
                Text("Add to MatchPost Queue")
                    .font(.title3.bold())
                Spacer()
                Button("Cancel", action: onCancel)
                    .buttonStyle(.plain)
                    .foregroundStyle(.secondary)
            }
            .padding()
            .background(.regularMaterial)

            Divider()

            ScrollView {
                VStack(spacing: 20) {
                    // Instagram card preview
                    instagramCard

                    // Date info
                    dateCard

                    // Queue position note
                    queueNote
                }
                .padding()
            }

            Divider()

            // Footer
            HStack {
                Button("Cancel", action: onCancel)
                    .buttonStyle(.bordered)
                Spacer()
                Button {
                    onAddToQueue()
                } label: {
                    Label("Add to Queue", systemImage: "tray.and.arrow.down.fill")
                        .font(.headline)
                }
                .buttonStyle(.borderedProminent)
            }
            .padding()
            .background(.regularMaterial)
        }
        .frame(width: 480, height: 560)
    }

    // MARK: - Sub-views

    private var instagramCard: some View {
        VStack(alignment: .leading, spacing: 0) {
            // "Instagram" header mock
            HStack {
                Circle()
                    .fill(Color.accentColor)
                    .frame(width: 32, height: 32)
                    .overlay(Text(player?.name.prefix(1) ?? "M")
                        .font(.caption.bold()).foregroundStyle(.white))
                Text(player?.instagramHandle.map { "@\($0)" } ?? player?.name ?? "Player")
                    .font(.subheadline.bold())
                Spacer()
            }
            .padding(10)
            .background(Color(.windowBackgroundColor))

            // Photo
            Image(nsImage: placeholderImage)
                .resizable()
                .scaledToFill()
                .frame(height: 260)
                .clipped()

            // Caption placeholder
            VStack(alignment: .leading, spacing: 4) {
                Text("Caption will be generated by Claude AI after match details are confirmed.")
                    .font(.caption)
                    .foregroundStyle(.secondary)
                Text("#voetbal #U14 #KNVB #dutchfootball")
                    .font(.caption)
                    .foregroundStyle(Color.accentColor)
            }
            .padding(10)
            .background(Color(.windowBackgroundColor))
        }
        .clipShape(RoundedRectangle(cornerRadius: 12))
        .shadow(color: .black.opacity(0.08), radius: 8, y: 4)
    }

    private var dateCard: some View {
        HStack {
            Image(systemName: "calendar")
                .foregroundStyle(.secondary)
            if let date = exifDate {
                VStack(alignment: .leading) {
                    Text("Photo taken")
                        .font(.caption).foregroundStyle(.secondary)
                    Text(date.formatted(date: .long, time: .shortened))
                        .font(.subheadline.bold())
                }
            } else {
                VStack(alignment: .leading) {
                    Text("No EXIF date found")
                        .font(.caption).foregroundStyle(.orange)
                    Text("This photo will post after all dated photos")
                        .font(.subheadline)
                }
            }
            Spacer()
        }
        .padding()
        .background(Color.secondary.opacity(0.08))
        .clipShape(RoundedRectangle(cornerRadius: 10))
    }

    private var queueNote: some View {
        HStack(alignment: .top, spacing: 10) {
            Image(systemName: "info.circle.fill")
                .foregroundStyle(.blue)
            Text("This photo will be placed in the MatchPost queue. Photos are always posted in chronological order — oldest first. Open MatchPost to review the queue and post.")
                .font(.caption)
                .foregroundStyle(.secondary)
        }
        .padding()
        .background(Color.blue.opacity(0.06))
        .clipShape(RoundedRectangle(cornerRadius: 10))
    }
}
